// bin2inc.c
//
// convert a binary file into a assembly source data
//
// THE "BEER-WARE LICENSE" (Revision 3.1415):
// sandro AT sigala DOT it wrote this file. As long as you retain this notice you can do
// whatever you want with this stuff.  If we meet some day, and you think this stuff is
// worth it, you can buy me a beer in return.  Sandro Sigala
//
// Modified for output assembly data by Khralkatorrix.
//
// syntax:  bin2inc2 <character height> <input_file> <output_file>
//
// examples:
//     bin2inc2 16 font.fon font.inc

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef PATH_MAX
#define PATH_MAX 1024
#endif

void process(const char *height, const char *ifname, const char *ofname)
{
    FILE *ifile, *ofile;
    const char *cp;
    int c, i, count = 0;
    int charheight = 15;        /* start count at 0 */
    int charpos = 0x00;
    unsigned int size;

    ifile = fopen(ifname, "rb");
    if (ifile == NULL)
    {
        fprintf(stderr, "cannot open %s for reading\n", ifname);
        exit(1);
    }
    ofile = fopen(ofname, "wb");
    if (ofile == NULL)
    {
        fprintf(stderr, "cannot open %s for writing\n", ofname);
        exit(1);
    }

    /* get input file size */
    fseek(ifile, 0, SEEK_END);
    size = ftell(ifile);
    fseek(ifile, 0, SEEK_SET);

    charheight = strtol(height, NULL, 10) - 1;

    /* VGA Thai font 8x16, Loxley code */
    if ((size == 1536) && (charheight == 15))
    {
        charpos = 0xa0;
    }
    /* EGA Thai font 8x14 */
    else if ((size == 1792) && (charheight == 13))
    {
        charpos = 0x80;
    }
    /* VGA Thai font 8x16 */
    else if ((size == 2048) && (charheight == 15))
    {
        charpos = 0x80;
    }

    /* strip path to only input file name */
    if ((cp = strrchr(ifname, '/')) != NULL)
    {
        ++cp;
    }
    else
    {
        if ((cp = strrchr(ifname, '\\')) != NULL)
        {
            ++cp;
        }
        else
        {
            cp = ifname;
        }
    }

    fprintf(ofile, "; %s\r\n", cp);
    fprintf(ofile, "; Generated by bin2inc\r\n\r\n");

    fprintf(ofile, "Font\tlabel\tbyte\r\n");
    while ((c = getc(ifile)) != EOF)
    {
        if (count == 0)
        {
            fprintf(ofile, "; 0x%.2xh\n", charpos);
        }

        /* print font data */
        fprintf(ofile, "\tdb\t");
        for(i = 0; i <= 7; i++)
        {
            fprintf(ofile, "%u", (c >> i) & 1);
        }
        fprintf(ofile, "b\t; ");

        /* print comment */
        for(i = 0; i <= 7; i++)
        {
            fprintf(ofile, "%c", (c & (1 << i)) ? '*' : '.');
        }
        fprintf(ofile, " %d\n", count);

        count++;
        if (count > charheight)
        {
            charpos++;
            count = 0;
        }
    }
    fprintf(ofile, "\r\n");

    fclose(ifile);
    fclose(ofile);
}

void usage(void)
{
    fprintf(stderr, "usage: bin2inc2 <character height> <input_file> <output_file>\n");
    exit(1);
}

int main(int argc, char **argv)
{
    while (argc > 4)
    {
        usage();
    }
    if (argc != 4)
    {
        usage();
    }
    process(argv[1], argv[2], argv[3]);
    return 0;
}
