# Thai Display Font makefile.

!ifndef assembler
!   define assembler wasm
!endif

!ifndef c_compiler
#!   define c_compiler wcc386
!   define c_compiler wcc
!endif

!ifndef linker
!   define linker wlink
!endif

!ifndef asm_options
!   define asm_options -zq -d1
!endif

!ifndef c_options
!   define c_options -zq -d1
!endif

.extensions:
.extensions: .com .exe .lnk .obj .c .asm

.asm.obj: .AUTODEPEND
    $(assembler) $(asm_options) $[*

.c.obj: .AUTODEPEND
    $(c_compiler) $(c_options) $[*

##############################################################################
# bin2inc.exe
##############################################################################

bin2inc: .SYMBOLIC bin2inc.exe

bin2inc_objs = bin2inc.obj

bin2inc.exe: $(bin2inc_objs) bin2inc.lnk
    $(linker) @bin2inc.lnk

bin2inc.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    bin2inc
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FILE    $(bin2inc_objs)
    #@for %i in ($(bin2inc_objs)) do @%append $@ FILE    %i

##############################################################################
# bin2inc2.exe
##############################################################################

bin2inc2: .SYMBOLIC bin2inc2.exe

bin2inc2_objs = bin2inc2.obj

bin2inc2.exe: $(bin2inc2_objs) bin2inc2.lnk
    $(linker) @bin2inc2.lnk

bin2inc2.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    bin2inc2
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FILE    $(bin2inc2_objs)
    #@for %i in ($(bin2inc2_objs)) do @%append $@ FILE    %i

##############################################################################
# rorg.com
##############################################################################

rorg: .SYMBOLIC rorg.com

rorg.com: rorg.obj rorg.lnk
    $(linker) @rorg.lnk

rorg.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rorg
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rorg.obj

##############################################################################
# codeku2.com
##############################################################################

codeku2: .SYMBOLIC codeku2.com

codeku2: bin2inc.exe
    echo .
#    bin2inc 14 codeku2.fon codeku2.inc

codeku2.com: codeku2.inc codeku2.obj codeku2.lnk
    $(linker) @codeku2.lnk

codeku2.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codeku2
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codeku2.obj

##############################################################################
# codeku3.com
##############################################################################

codeku3: .SYMBOLIC codeku3.com

codeku3: bin2inc.exe
    echo .
#    bin2inc 16 codeku3.fon codeku3.inc

codeku3.com: codeku3.inc codeku3.obj codeku3.lnk
    $(linker) @codeku3.lnk

codeku3.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codeku3
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codeku3.obj

##############################################################################
# codesic.com
##############################################################################

codesic: .SYMBOLIC codesic.com

codesic: bin2inc.exe
    echo .
#    bin2inc 14 codesic.fon codesic.inc

codesic.com: codesic.inc codesic.obj codesic.lnk
    $(linker) @codesic.lnk

codesic.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codesic
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codesic.obj

##############################################################################
# codesic2.com
##############################################################################

codesic2: .SYMBOLIC codesic2.com

codesic2: bin2inc.exe
    echo .
#    bin2inc 14 codesic2.fon codesic2.inc

codesic2.com: codesic2.inc codesic2.obj codesic2.lnk
    $(linker) @codesic2.lnk

codesic2.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codesic2
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codesic2.obj

##############################################################################
# codesic3.com
##############################################################################

codesic3: .SYMBOLIC codesic3.com

codesic3: bin2inc.exe
    echo .
#    bin2inc 16 codesic3.fon codesic3.inc

codesic3.com: codesic3.inc codesic3.obj codesic3.lnk
    $(linker) @codesic3.lnk

codesic3.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codesic3
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codesic3.obj

##############################################################################
# lyvga.com
##############################################################################

lyvga: .SYMBOLIC lyvga.com

lyvga.com: lyvga.obj lyvga.lnk
    $(linker) @lyvga.lnk

lyvga.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    lyvga
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    lyvga.obj

##############################################################################
# qx10.com
##############################################################################

qx10: .SYMBOLIC qx10.com

qx10.inc: bin2inc2.exe
    echo .
#    bin2inc2 16 qx10.fon qx10.inc

qx10.com: qx10.inc qx10.obj qx10.lnk
    $(linker) @qx10.lnk

qx10.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    qx10
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    qx10.obj

##############################################################################
# rega.com
##############################################################################

rega: .SYMBOLIC rega.com

rega.inc: bin2inc.exe
    echo .
#    bin2inc 14 rega.fon rega.inc

rega.com: rega.inc rega.obj rega.lnk
    $(linker) @rega.lnk

rega.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rega
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rega.obj

##############################################################################
# rvga.com
##############################################################################

rvga: .SYMBOLIC rvga.com

rvga.inc: bin2inc.exe
    echo .
#    bin2inc 16 rvga.fon rvga.inc

rvga.com: rvga.inc rvga.obj rvga.lnk
    $(linker) @rvga.lnk

rvga.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rvga
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rvga.obj

##############################################################################
# tgaplus.com
##############################################################################

tgaplus: .SYMBOLIC tgaplus.com

tgaplus.com: tgaplus.inc tgaplus.obj tgaplus.lnk
    $(linker) @tgaplus.lnk

tgaplus.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    tgaplus
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    tgaplus.obj

##############################################################################
# thaicour.com
##############################################################################

thaicour: .SYMBOLIC thaicour.com

thaicour.inc: bin2inc.exe
    echo .
#    bin2inc 16 thaicour.fon thaicour.inc

thaicour.com: thaicour.inc thaicour.obj thaicour.lnk
    $(linker) @thaicour.lnk

thaicour.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    thaicour
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    thaicour.obj

##############################################################################
# tsme.com
##############################################################################

tsme: .SYMBOLIC tsme.com

tsme: bin2inc.exe
    echo .
#    bin2inc 14 tsme.fon tsme.inc

tsme.com: tsme.inc tsme.obj tsme.lnk
    $(linker) @tsme.lnk

tsme.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    tsme
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    tsme.obj

##############################################################################
# tsmv.com
##############################################################################

tsmv: .SYMBOLIC tsmv.com

tsmv: bin2inc.exe
    echo .
#    bin2inc 16 tsmv.fon tsmv.inc

tsmv.com: tsmv.inc tsmv.obj tsmv.lnk
    $(linker) @tsmv.lnk

tsmv.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    tsmv
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    tsmv.obj

##############################################################################

all: bin2inc bin2inc2 rorg codeku2 codeku3 codesic codesic2 codesic3 lyvga qx10 rega rvga tgaplus thaicour tsme tsmv

clean: .SYMBOLIC
    @if exist *.com del *.com
    @if exist *.exe del *.exe
    @if exist *.lnk del *.lnk
    @if exist *.obj del *.obj
    @if exist *.map del *.map
    @if exist *.err del *.err
    @if exist *.sym del *.sym
